### ISSUE TITLE
override default server variable

### ISSUE THREAD

**Issue by adriensaladin** [jaytaylor/ansible-kafka#36]
Hi,

I had to override server.advertised_listeners, which is defined in the default role variables, and it was quite a difficult task. 

I asked a coworker which knows Ansible much better than I and the best method we found so far is to use `pre_tasks` as bellow:

```
- hosts: kafka
  roles:
    - role: ansible-kafka
      kafka_hosts: "{{ ansible_play_batch }}"
      kafka_version: 1.0.0     # Kafka version override.

  vars:
    zookeeper_hosts: "kafka1-1:2181,kafka1-2:2181,kafka1-3:2181"
    kafka_zookeeper_hosts: ['kafka1-1', 'kafka1-2', 'kafka1-3']

  pre_tasks:
    - name: set advertised listeners
      set_fact:
        server: '{{ server | combine({"advertised_listeners": "PLAINTEXT://"+ansible_hostname+":9092" }) }}'
```

The thing is we either need to completely redefine the `server` dict in the ansible play, or change the Ansible merge strategy in ansible.cfg (which is generally a bad idea) or use this `set_fact` trick.

Are you aware of a better method to redefine those variables ? If not, would you like to add an example in the role documentation?

Cheers,
